### ISSUE TITLE
exceptions.RuntimeError: Copyable subclasses must specify 'typeToCopy'

### ISSUE THREAD

**Issue by exarkun** [PrivateStorageio/ZKAPAuthorizer#179]
The Tahoe-LAFS storage server now logs about two of these tracebacks:

```
2020-09-14T02:42:17+0000 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-09-14T02:42:17+0000 [twisted.internet.defer#critical]
        Traceback (most recent call last):
          File "/nix/store/sbgsnp92qlklmxvj3qfjjkiplsz36958-python-2.7.17-env/lib/python2.7/site-packages/foolscap/slicers/root.py", line 107, in send
            d.callback(None)
          File "/nix/store/sbgsnp92qlklmxvj3qfjjkiplsz36958-python-2.7.17-env/lib/python2.7/site-packages/twisted/internet/defer.py", line 460, in callback
            self._startRunCallbacks(result)
          File "/nix/store/sbgsnp92qlklmxvj3qfjjkiplsz36958-python-2.7.17-env/lib/python2.7/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
            self._runCallbacks()
          File "/nix/store/sbgsnp92qlklmxvj3qfjjkiplsz36958-python-2.7.17-env/lib/python2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
        --- <exception caught here> ---
          File "/nix/store/sbgsnp92qlklmxvj3qfjjkiplsz36958-python-2.7.17-env/lib/python2.7/site-packages/foolscap/banana.py", line 198, in produce
            obj = next()
          File "/nix/store/sbgsnp92qlklmxvj3qfjjkiplsz36958-python-2.7.17-env/lib/python2.7/site-packages/foolscap/copyable.py", line 50, in slice
            copytype = self.obj.getTypeToCopy()
          File "/nix/store/sbgsnp92qlklmxvj3qfjjkiplsz36958-python-2.7.17-env/lib/python2.7/site-packages/foolscap/copyable.py", line 40, in getTypeToCopy
            raise RuntimeError("Copyable subclasses must specify 'typeToCopy'")
        exceptions.RuntimeError: Copyable subclasses must specify 'typeToCopy'
```

every time a client manages to connect to it.

An inspection of the server's Foolscal log ("flog") reveals:

```
12:33:18.549 L10 []#3211 Negotiate.switchToBanana(isClient=False)
12:33:18.549 L10 []#3212 params: {'current-seqnum': 1, 'banana-decision-version': 3, 'current-slave-IR': '5169ba75fd87fd70', 'initial-vocab-table-index': 1}
12:33:19.012 L20 []#3213 storage: slot_readv enagkycffidw5qzdhqvw6mx2dq []
12:33:19.012 L10 []#3214 returning shares [0]
12:33:19.022 L20 []#3215 storage: get_buckets h3j3wcidx44f5s6uq45wusqqc4
12:33:19.023 L20 []#3216 storage: slot_readv z27edy6afz5k2hiaotseucyjpa []
12:33:19.023 L10 []#3217 returning shares [0]                                                                                                                                                                                               
12:33:19.152 L20 []#3218 storage: slot_readv ndaf3rexflxiuqh3snl74lzjd4 []
12:33:19.152 L10 []#3219 returning shares [0]                                                                                                                                                                     
12:33:19.164 L20 []#3220 storage: slot_readv nnnhipfobewdjzswxwespwu7he []                                                                                                                                                  
12:33:19.164 L10 []#3221 returning shares [0]                                                                                                                                                                          
12:33:19.299 L20 []#3222 storage: allocate_buckets h3j3wcidx44f5s6uq45wusqqc4                                    
12:33:19.301 L20 []#3223 storage: slot_readv mjwd6uup3tsqi2pl64e4oevjqy []                                                                                                                                
12:33:19.301 L10 []#3224 returning shares [0]                                                                                                                                                            
12:33:19.442 L20 []#3225 storage: slot_readv ndaf3rexflxiuqh3snl74lzjd4 []                                                                                                                                       
12:33:19.442 L10 []#3226 returning shares [0]                                      
12:33:19.453 L20 []#3227 storage: slot_readv enagkycffidw5qzdhqvw6mx2dq []                   
12:33:19.453 L10 []#3228 returning shares [0]                                          
12:33:19.565 L20 []#3229 storage: slot_readv mjwd6uup3tsqi2pl64e4oevjqy []           
12:33:19.565 L10 []#3230 returning shares [0]                                                                                                                                                    
12:33:19.576 L20 []#3231 storage: slot_readv z27edy6afz5k2hiaotseucyjpa []
12:33:19.576 L10 []#3232 returning shares [0]                                                                                                                                                         
12:33:19.726 L20 []#3233 storage: slot_readv ndaf3rexflxiuqh3snl74lzjd4 []            
12:33:19.727 L10 []#3234 returning shares [0]                                                                                                                                                                   
12:33:19.869 L20 []#3235 storage: slot_readv mjwd6uup3tsqi2pl64e4oevjqy [0]
12:33:19.869 L10 []#3236 returning shares [0]                                                                                                                                                              
12:33:20.191 L20 []#3237 storage: slot_readv mjwd6uup3tsqi2pl64e4oevjqy []
12:33:20.191 L10 []#3238 returning shares [0]
12:33:20.226 L20 []#3239 connection to 5fdg lost
```

(which tells *me* approximately nothing).

**Comment by exarkun** [comment]
Introduced by https://github.com/PrivateStorageio/ZKAPAuthorizer/commit/cfd70c00fe066373ca02e5dd48cdaf55069aeedb which changed the client to call "stat_shares" which returns a `ShareStat` which turns out to not be a completed implemented Copyable.
