### ISSUE TITLE
Broken against recent Tahoe-LAFS master@HEAD

### ISSUE THREAD

**Issue by exarkun** [PrivateStorageio/ZKAPAuthorizer#224]
```
Unhandled Error
Traceback (most recent call last):
  File "/nix/store/2jsiq3gnn0b61kzvmjqmwpqm0al8k95g-python2.7-Twisted-18.9.0/lib/python2.7/site-packages/twisted/scripts/trial.py", line 478, in postOptions                                 
    _BasicOptions.postOptions(self)
  File "/nix/store/2jsiq3gnn0b61kzvmjqmwpqm0al8k95g-python2.7-Twisted-18.9.0/lib/python2.7/site-packages/twisted/scripts/trial.py", line 388, in postOptions                                 
    self['reporter'] = self._loadReporterByName(self['reporter'])
  File "/nix/store/2jsiq3gnn0b61kzvmjqmwpqm0al8k95g-python2.7-Twisted-18.9.0/lib/python2.7/site-packages/twisted/scripts/trial.py", line 375, in _loadReporterByName                         
    for p in plugin.getPlugins(itrial.IReporter):
  File "/nix/store/2jsiq3gnn0b61kzvmjqmwpqm0al8k95g-python2.7-Twisted-18.9.0/lib/python2.7/site-packages/twisted/plugin.py", line 213, in getPlugins                                         
    allDropins = getCache(package)
--- <exception caught here> ---
  File "/nix/store/2jsiq3gnn0b61kzvmjqmwpqm0al8k95g-python2.7-Twisted-18.9.0/lib/python2.7/site-packages/twisted/plugin.py", line 171, in getCache                                           
    provider = pluginModule.load()
  File "/nix/store/2jsiq3gnn0b61kzvmjqmwpqm0al8k95g-python2.7-Twisted-18.9.0/lib/python2.7/site-packages/twisted/python/modules.py", line 392, in load                                       
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/nix/store/2jsiq3gnn0b61kzvmjqmwpqm0al8k95g-python2.7-Twisted-18.9.0/lib/python2.7/site-packages/twisted/python/reflect.py", line 308, in namedAny                                   
    topLevelPackage = _importAndCheckStack(trialname)
  File "/nix/store/2jsiq3gnn0b61kzvmjqmwpqm0al8k95g-python2.7-Twisted-18.9.0/lib/python2.7/site-packages/twisted/python/reflect.py", line 247, in _importAndCheckStack                       
    return __import__(importName)
  File "/nix/store/l2g4r74cqssw1pn1f64drqj4igxj51bh-python2.7-zero-knowledge-access-pass-authorizer-0.0/lib/python2.7/site-packages/twisted/plugins/zkapauthorizer.py", line 19, in <module> 
    from _zkapauthorizer.api import (
  File "/nix/store/l2g4r74cqssw1pn1f64drqj4igxj51bh-python2.7-zero-knowledge-access-pass-authorizer-0.0/lib/python2.7/site-packages/_zkapauthorizer/api.py", line 26, in <module>            
    from ._storage_server import (
  File "/nix/store/l2g4r74cqssw1pn1f64drqj4igxj51bh-python2.7-zero-knowledge-access-pass-authorizer-0.0/lib/python2.7/site-packages/_zkapauthorizer/_storage_server.py", line 96, in <module>
    from .foolscap import (
  File "/nix/store/l2g4r74cqssw1pn1f64drqj4igxj51bh-python2.7-zero-knowledge-access-pass-authorizer-0.0/lib/python2.7/site-packages/_zkapauthorizer/foolscap.py", line 145, in <module>      
    class RIPrivacyPassAuthorizedStorageServer(RemoteInterface):
  File "/nix/store/l2g4r74cqssw1pn1f64drqj4igxj51bh-python2.7-zero-knowledge-access-pass-authorizer-0.0/lib/python2.7/site-packages/_zkapauthorizer/foolscap.py", line 165, in RIPrivacyPassAu
thorizedStorageServer
    renew_lease = add_passes(RIStorageServer["renew_lease"])
  File "/nix/store/iz5d93w5av65zmlgmp9giknz41la0n65-python2.7-zope.interface-4.6.0/lib/python2.7/site-packages/zope/interface/interface.py", line 423, in getDescriptionFor                  
    raise KeyError(name)
exceptions.KeyError: 'renew_lease'
```

**Comment by exarkun** [comment]
Fixed in #231 via #228
