### ISSUE TITLE
_zkapauthorizer.tests.test_plugin.ClientPluginTests.test_mismatched_ristretto_issuer fails against a recent Tahoe-LAFS

### ISSUE THREAD

**Issue by exarkun** [PrivateStorageio/ZKAPAuthorizer#225]
```
[ERROR]
Traceback (most recent call last):
Failure: testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/nix/store/5i2vxdkgqwyhxn045rl82swfzdfnx259-python2.7-zero-knowledge-access-pass-authorizer-0.0/lib/python2.7/site-packages/_zkapauthorizer/tests/test_plugin.py", line 389, in test_mismatched_ristretto_issuer
    def test_mismatched_ristretto_issuer(self, config_text, announcement):
  File "/nix/store/292g23l2sr0bjp68c2zz1v9qjkqfwl37-python2.7-hypothesis-4.7.3/lib/python2.7/site-packages/hypothesis/core.py", line 974, in wrapped_test                                    
    state.run()
  File "/nix/store/292g23l2sr0bjp68c2zz1v9qjkqfwl37-python2.7-hypothesis-4.7.3/lib/python2.7/site-packages/hypothesis/core.py", line 695, in run                                             
    info.__expected_traceback,
  File "/nix/store/292g23l2sr0bjp68c2zz1v9qjkqfwl37-python2.7-hypothesis-4.7.3/lib/python2.7/site-packages/hypothesis/core.py", line 568, in execute                                         
    result = self.test_runner(data, run)
  File "/nix/store/292g23l2sr0bjp68c2zz1v9qjkqfwl37-python2.7-hypothesis-4.7.3/lib/python2.7/site-packages/hypothesis/executors.py", line 56, in default_new_style_executor                  
    return function(data)
  File "/nix/store/292g23l2sr0bjp68c2zz1v9qjkqfwl37-python2.7-hypothesis-4.7.3/lib/python2.7/site-packages/hypothesis/core.py", line 566, in run                                             
    return test(*args, **kwargs)
  File "/nix/store/5i2vxdkgqwyhxn045rl82swfzdfnx259-python2.7-zero-knowledge-access-pass-authorizer-0.0/lib/python2.7/site-packages/_zkapauthorizer/tests/test_plugin.py", line 401, in test_mismatched_ristretto_issuer
    node_config.config.write(config_text)
  File "/nix/store/blxv6xxjy5w00y4w0l9sby87jxbdprv1-python2.7-configparser-3.7.4/lib/python2.7/site-packages/backports/configparser/__init__.py", line 931, in write                         
    self._sections[section].items(), d)
  File "/nix/store/blxv6xxjy5w00y4w0l9sby87jxbdprv1-python2.7-configparser-3.7.4/lib/python2.7/site-packages/backports/configparser/__init__.py", line 935, in _write_section                
    fp.write("[{0}]\n".format(section_name))
TypeError: 'unicode' does not have the buffer interface


_zkapauthorizer.tests.test_plugin.ClientPluginTests.test_mismatched_ristretto_issuer
```

**Comment by exarkun** [comment]
Fixed in #232 via #228
