### ISSUE TITLE
lease maintenance code cannot call `stat_shares`

### ISSUE THREAD

**Issue by exarkun** [PrivateStorageio/ZKAPAuthorizer#83]
It fails with a Foolscap violation:

```
2020-02-25T15:40:33-0500 [-] Fuzzy timer service (lease maintenance service)
        Traceback (most recent call last):
          File "/nix/store/4ba7dicrqyiazsmwgqjj8p9xwx800gap-python-2.7.17-env/lib/python2.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred                                                  
            result = f(*args, **kw)
          File "/nix/store/4ba7dicrqyiazsmwgqjj8p9xwx800gap-python-2.7.17-env/lib/python2.7/site-packages/_zkapauthorizer/lease_maintenance.py", line 402, in <lambda>                                            
            maintain_leases,
          File "/nix/store/4ba7dicrqyiazsmwgqjj8p9xwx800gap-python-2.7.17-env/lib/python2.7/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator                                               
            return _cancellableInlineCallbacks(gen)
          File "/nix/store/4ba7dicrqyiazsmwgqjj8p9xwx800gap-python-2.7.17-env/lib/python2.7/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks                                   
            _inlineCallbacks(None, g, status)
        --- <exception caught here> ---
          File "/nix/store/4ba7dicrqyiazsmwgqjj8p9xwx800gap-python-2.7.17-env/lib/python2.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks                                              
            result = g.send(result)
          File "/nix/store/4ba7dicrqyiazsmwgqjj8p9xwx800gap-python-2.7.17-env/lib/python2.7/site-packages/_zkapauthorizer/controller.py", line 750, in bracket                                                    
            result = yield between()
        foolscap.tokens.Violation: Violation: ('RIStorageServer.tahoe.allmydata.com(<RemoteReference at 0x7fc143290c10 [pb://ysj4...@tcp:x.x.x.x:8898/3nml...]>) does not offer stat_shares',)
```

**Comment by exarkun** [comment]
It looks like the client is trying to talk to an anonymous-access storage server instead of a ZKAPAuthorizer storage server.  This is ultimately due to a misconfiguration of the client but it would be great if this misconfiguration were reported in a more understandable manner.
